### ISSUE TITLE
Fail to import

### ISSUE THREAD

**Issue by n4zmz** [devopsarr/terraform-provider-prowlarr#148]
Sonarr/Radarr are working fine.  Prowlarr is failing to import anything I specify.

DENNISs-Mac-mini:terraform dennis$ terraform -v
Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/devopsarr/prowlarr v1.5.0
+ provider registry.terraform.io/devopsarr/radarr v1.8.0
+ provider registry.terraform.io/devopsarr/sonarr v2.8.0
+ provider registry.terraform.io/devopsarr/whisparr v1.2.0
+ provider registry.terraform.io/hashicorp/vsphere v2.3.1
+ provider registry.terraform.io/shihanng/installer v0.3.0

Prowlarr version: 1.3.1.2796

Example below

DENNISs-Mac-mini:terraform dennis$ terraform import prowlarr_download_client.prowlarr-nzbget 1
prowlarr_download_client.prowlarr-nzbget: Importing from ID "1"...
prowlarr_download_client.prowlarr-nzbget: Import prepared!
  Prepared prowlarr_download_client for import
prowlarr_download_client.prowlarr-nzbget: Refreshing state...
data.vsphere_datacenter.dc: Reading...
data.vsphere_datacenter.dc: Read complete after 0s [id=datacenter-1001]
data.vsphere_compute_cluster.cluster: Reading...
data.vsphere_network.network: Reading...
data.vsphere_datastore.datastore: Reading...
data.vsphere_network.network: Read complete after 0s [id=network-1011]
data.vsphere_compute_cluster.cluster: Read complete after 0s [id=domain-c1018]
data.vsphere_datastore.datastore: Read complete after 0s [id=datastore-2002]
╷
│ Error: Client Error
│ 
│ Unable to read download_client, got error: 404 Not Found
│ Details:
│ {
│   "message": "DownloadClientDefinition with ID 1 does not exist",
│   "description": "NzbDrone.Core.Datastore.ModelNotFoundException: DownloadClientDefinition with ID 1 does not exist\n   at NzbDrone.Core.Datastore.BasicRepository\u00601.Get(Int32 id) in D:\\a\\1\\s\\src\\NzbDrone.Core\\Datastore\\BasicRepository.cs:line 96\n   at Prowlarr.Api.V1.ProviderControllerBase\u00603.GetResourceById(Int32 id) in D:\\a\\1\\s\\src\\Prowlarr.Api.V1\\ProviderControllerBase.cs:line 37\n   at lambda_method323(Closure , Object , Object[] )\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Prowlarr.Http\\Middleware\\BufferingMiddleware.cs:line 28\n   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Prowlarr.Http\\Middleware\\IfModifiedMiddleware.cs:line 41\n   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Prowlarr.Http\\Middleware\\CacheHeaderMiddleware.cs:line 33\n   at Prowlarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Prowlarr.Http\\Middleware\\StartingUpMiddleware.cs:line 38\n   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Prowlarr.Http\\Middleware\\UrlBaseMiddleware.cs:line 27\n   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Prowlarr.Http\\Middleware\\VersionMiddleware.cs:line 28\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"
│ }
╵

**Comment by Fuochi** [comment]
Hi @n4zmz,
Thanks for opening the issue. I'll have a look in the next few days.
Still, it's a weird error because this should be checked by the acceptance tests, and the 404 response is coming from prowlarr itself.
I'll try to replicate and come back to you.

**Comment by Fuochi** [comment]
Hi @n4zmz,
Did you manage to get at the bottom of this?

**Comment by Fuochi** [comment]
Hi @n4zmz,
If you don't have anything to add here, I'll close this ticket by the end of the week.

**Comment by Fuochi** [comment]
closing since there is no update.
