### ISSUE TITLE
Idempotency of resources

### ISSUE THREAD

**Issue by jdmcmahan** [devopsarr/terraform-provider-prowlarr#207]
Hi!

I've noticed that this provider will attempt to recreate existing resources under certain scenarios involving the local Terraform state. For example, after restructuring some `.tf` files I received the following error:

```
module.proxies.prowlarr_indexer_proxy_flaresolverr.flaresolverr: Creating...
╷
│ Error: Client Error
│ 
│   with module.proxies.prowlarr_indexer_proxy_flaresolverr.flaresolverr,
│   on modules/proxies/main.tf line 1, in resource "prowlarr_indexer_proxy_flaresolverr" "flaresolverr":
│    1: resource "prowlarr_indexer_proxy_flaresolverr" "flaresolverr" {
│ 
│ Unable to create indexer_proxy_flaresolverr, got error: 400 Bad Request
│ Details:
│ [
│   {
│     "propertyName": "Name",
│     "errorMessage": "Should be unique",
│     "attemptedValue": "FlareSolverr",
│     "severity": "error",
│     "errorCode": "PredicateValidator",
│     "formattedMessageArguments": [],
│     "formattedMessagePlaceholderValues": {
│       "PropertyName": "Name",
│       "PropertyValue": "FlareSolverr"
│     }
│   }
│ ]
```

This is easily reproducible by running `terraform apply`, deleting the Terraform state files, and then running `terraform apply` again.

Is this the expected behavior? It seems that the provider only compares against the local Terraform state, not the actual runtime state of the *arr application.

Thanks in advance!

**Comment by Fuochi** [comment]
Hi @jdmcmahan,
Yes, this is the expected behaviour of a terraform provider. You could use terraform import in order to add already existing resources to state.

**Comment by jdmcmahan** [comment]
Thanks @Fuochi ! That makes sense. This is a bit different from some other providers I've used so just wanted to make sure.

For anyone curious, this seems to work pretty well (although I suspect the `import`blocks would have to be added after the resource is created to avoid `404`s):

```hcl
import {
  to = prowlarr_indexer_proxy_flaresolverr.flaresolverr
  id = "1"
}

resource "prowlarr_indexer_proxy_flaresolverr" "flaresolverr" {
  host            = "http://flaresolverr.whatever"
  name            = "FlareSolverr"
  ...
}
```
